{% set name = "ai2-olmo" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ai2-olmo-{{ version }}.tar.gz
  sha256: 575443c9c1b8db826d1503426010efd08d03f536ccde363470009370a3df0e0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - pytorch >=2.0,<2.2
    - omegaconf
    - rich
    - boto3
    - google-cloud-storage
    - tokenizers
    - packaging
    - cached_path
    - transformers

test:
  imports:
    - hf_olmo
    - olmo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/allenai/OLMo
  summary: Open Language Model (OLMo)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
